agent_name: topic_aggregator
author: arcolife
version: 0.1.0
license: Apache-2.0
description: ''
aea_version: '>=1.15.0, <2.0.0'
fingerprint: {}
fingerprint_ignore_patterns: []
connections: []
contracts: []
protocols: []
skills:
- arcolife/topic_extractor:0.1.0:bafybeib3zl6sbwz45jaxx3jetznlddsr3ez7zqfbrowtqnz5vktcaz4ib4
default_ledger: ethereum
required_ledgers:
- ethereum
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  disable_existing_loggers: false
  version: 1
  # formatters:
  #   standard:
  #     format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
  # handlers:
  #   logfile:
  #     class: logging.FileHandler
  #     formatter: standard
  #     level: DEBUG
  #     filename: logconfig.log
  #   console:
  #     class: logging.StreamHandler
  #     formatter: standard
  #     level: DEBUG
  # loggers:
  #   topic_logger:
  #     handlers:
  #     - logfile
  #     - console
  #     level: DEBUG
  #     propagate: False
dependencies:
  open-aea-ledger-ethereum: {}
default_connection: null
---
# public_id: fetchai/http_server:0.22.0
# type: connection
# config:
#   host: ${HOST:str:localhost}
#   port: ${PORT:int:5000}
#   target_skill_id: ${TARGET_SKILL:str:fetchai/http_echo:0.20.0}